### ISSUE TITLE
Temporary private forks for resolving security vulnerabilities in open source projects

### ISSUE THREAD

**Issue by wrslatz** [github-community-projects/private-mirrors#106]
### Is your feature request related to a problem?

GitHub has a feature for [collaborating in a temporary private fork to resolve a repository security vulnerability](https://docs.github.com/en/enterprise-cloud@latest/code-security/security-advisories/working-with-repository-security-advisories/collaborating-in-a-temporary-private-fork-to-resolve-a-repository-security-vulnerability). Developers within enterprises may want to collaborate on resolving security vulnerabilities in open source. They may be particularly interested in fixing the vulnerability due to impact within their enterprise or may have necessary expertise to contribute a vulnerability fix to the project.

### Describe the solution you'd like

Support temporary private forks for resolving a security vulnerability within Internal Contribution Forks, if possible.

### Describe alternatives you've considered

I'm not familiar with how temporary private forks for resolving a security vulnerability actually work within GitHub. There may be limitations in how they sync back to a user or organization repository that does not align with how ICF supports syncing back to a public fork.

**Comment by ahpook** [comment]
Grooming through these issues - I'm going to close this one out @wrslatz. Private vulnerability reporting has a really specific workflow that incorporates disclosure and CVE assignment, which we're not going to address here.

The point is well taken though - as we're thinking about incorporating private forks as a core feature, we should include the private vuln reporting use case so that it's less of a one-off flow than it is today.
